# Generated by Django 3.2.8 on 2021-10-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20211029_1952'),
        ('admins', '0003_auto_20210305_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='taskreportstudent',
            name='task_report',
        ),
        migrations.AlterField(
            model_name='archive',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='StudentAttend',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskReport',
        ),
        migrations.DeleteModel(
            name='TaskReportStudent',
        ),
        migrations.DeleteModel(
            name='TaskSession',
        ),
    ]
